=== hbaltz/ProjetXML/xml/tsi2016Final.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  targetNamespace="http://www.ensg.eu/tsi2016"
  xmlns:tsi2016="http://www.ensg.eu/tsi2016"
  >

  <element name="tsi2016">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" ref="tsi2016:Personne"/>
        <element maxOccurs="unbounded" ref="tsi2016:Employeur"/>
        <element minOccurs="0" maxOccurs="unbounded" ref="tsi2016:Lieu"/>
      </sequence>
    </complexType>
  </element>

  <element name="Personne">
    <complexType>
      <sequence>
        <element ref="tsi2016:Fonction"/>
      </sequence>
      <attribute name="employeur" use="required" type="string"/>
      <attribute name="lieu" use="required" type="string"/>
      <attribute name="nom" use="required" type="string"/>
      <attribute name="prenom" use="required" type="string"/>
      <attribute name="service" use="required" type="string"/>
    </complexType>
  </element>

   <simpleType name="roles">
    <restriction base="string">
      <enumeration value="etudiant" />
      <enumeration value="eleveFonctionnaire" />
      <enumeration value="eleveIngenieur" />
      <enumeration value="enFormationContinue" />
    </restriction>
  </simpleType>

  <element name="Fonction">
    <complexType>
      <attribute name="role" use="required" type="tsi2016:roles"/>
    </complexType>
  </element>

  <element name="Employeur">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" ref="tsi2016:Direction"/>
      </sequence>
      <attribute name="nom" use="required" type="string"/>
    </complexType>
  </element>

  <element name="Direction">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" ref="tsi2016:Service"/>
      </sequence>
      <attribute name="nom" use="required" type="string"/>
    </complexType>
  </element>

   <element name="Service">
    <complexType>
      <attribute name="nom" use="required" type="string"/>
      <attribute name="agents" use="required" type="integer"/>
    </complexType>
  </element>

   <element name="Lieu">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" ref="tsi2016:Adresse"/>
        <element minOccurs="0" ref="tsi2016:Coordonnee"/>
      </sequence>
      <attribute name="nom" use="required" type="string"/>
    </complexType>
  </element>

  <element name="Coordonnee">
    <complexType>
      <attribute name="lat" use="required" type="double"/>
      <attribute name="long" use="required" type="double"/>
    </complexType>
  </element>

   <element name="Adresse">
    <complexType>
      <attribute name="codePostal" use="required" type="integer"/>
      <attribute name="no" use="required" type="integer"/>
      <attribute name="rue" use="required" type="string"/>
      <attribute name="ville" use="required" type="string"/>
    </complexType>
  </element>

</schema>

=== hbaltz/ProjetXML/xml/tsi2016Final.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tsi2016 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="tsi2016Final.xsd"
	xmlns="http://www.ensg.eu/tsi2016"
    xmlns:tsi2016="http://www.ensg.eu/tsi2016">

	<Personne nom="hamya" prenom="hind" employeur="ENSG" service="ENSG.ERD.IST" lieu="lENSG">
	     <Fonction role="etudiant"/>
	</Personne>

	<Personne nom="derbouz" prenom="hanane" employeur="UPEM" service="UPEM.ERD.IST" lieu="lENSG">
	   	 <Fonction role="etudiant"/>
	</Personne>

	<Personne nom="BALTZ" prenom="Hugo" employeur="ENSG" service="ENSG.DRE.DE" lieu="lENSG">
		<Fonction role="eleveIngenieur"/>
	</Personne>

	<Personne nom="BRINON" prenom="Victor" employeur="ENSG" service="ENSG.DRE.DE" lieu="lENSG">
		<Fonction role="eleveFonctionnaire"/>
	</Personne>

	<Personne nom="MILLET" prenom="Rudolf" employeur="ENSG" service="ENSG.Direction_des_Etudes.TSI" lieu="lENSG">
		<Fonction role="eleveIngenieur"/>
	</Personne>

	<Personne nom="Er-razki" prenom="Sibawaih" employeur="ENSG" service="ENSG.DRE.Ministere_de_l_ecologie" lieu="lENSG">
		<Fonction role="eleveIngenieur"/>
	</Personne>

	<Personne nom="SLIM" prenom="Anas" employeur="UPEM" service="UPEM.DRE.Ministere_de_l_enseignement_sup" lieu="lENSG">
	    <Fonction role="etudiant"/>
	</Personne>
  
	<Personne nom="Marcuzzi" prenom="Julie" employeur="ENSG" service="ENSG.DRE.Direction_des_etudes" lieu="lENSG">
		<Fonction role="eleveFonctionnaire"/>   	
	</Personne>

	<Personne nom="Darroman" prenom="Elsa" employeur="ENSG" service="ENSG.DRE.Direction_des_etudes" lieu="lENSG">
		<Fonction role="eleveIngenieur"/>
	</Personne>

	<Personne nom="Benkimoun" prenom="Samuel" employeur="UPEM" service="UPEM.ERD.IST" lieu="lENSG">
		<Fonction role="etudiant"/>
	</Personne>

	<Personne nom="Samassa" prenom="Mamady" employeur="ENSG" service="ENSG.Direction_des_Etudes.TSI" lieu="lENSG">
		<Fonction role="eleveIngenieur"/>
	</Personne>

	<Personne nom="LESSAM" prenom="Coil" employeur="ENSG" service="ENSG.Direction_des_Etudes.TSI" lieu="lENSG">
		<Fonction role="etudiant"/> 
	</Personne>

	<Personne nom="Parisel" prenom="Camille" employeur="ENSG" service="ENSG.Direction_des_Etudes.TSI" lieu="lENSG">
		<Fonction role="eleveFonctionnaire"/> 
	</Personne>

	<Personne nom="MAZIERE" prenom="Romain" employeur="UPEM" service="UPEM.ERD.IST" lieu="lENSG">
		<Fonction role="enFormationContinue"/> 
	</Personne>	

	<Employeur nom="ENSG">
		<Direction nom="ENSG.DRE">
			<Service nom="ENSG.DRE.Direction_des_etudes" agents="200"/>
			<Service nom="ENSG.DRE.Ministere_de_l_ecologie" agents="120"/>
			<Service nom="ENSG.DRE.DE" agents="120"/>
	   	 </Direction>
		<Direction nom="ENSG.Direction_des_Etudes">
			<Service nom="ENSG.Direction_des_Etudes.TSI" agents="120"/>
	   	 </Direction>
		<Direction nom="ENSG.Ressource_humaine">
			<Service nom="ENSG.Ressource_humaine.DE" agents="120"/>
	   	 </Direction>
		<Direction nom="ENSG.ERD">
			<Service nom="ENSG.ERD.IST" agents="14"/>
	   	 </Direction>
	</Employeur>

	<Employeur nom="UPEM">
		<Direction nom="UPEM.DRE">
			<Service nom="UPEM.DRE.Direction_des_etudes" agents="200"/>
			<Service nom="UPEM.DRE.Ministere_de_l_enseignement_sup" agents="1220"/>
			<Service nom="UPEM.DRE.DE" agents="120"/>
	   	 </Direction>
		<Direction nom="UPEM.Direction_des_Etudes">
			<Service nom="UPEM.Direction_des_Etudes.TSI" agents="120"/>
	   	 </Direction>
		<Direction nom="UPEM.Ressource_humaine">
			<Service nom="UPEM.Ressource_humaine.DE" agents="120"/>
	   	 </Direction>
		<Direction nom="UPEM.ERD">
			<Service nom="UPEM.ERD.IST" agents="14"/>
	   	 </Direction>
	</Employeur>

	<Lieu nom="lENSG">
		 <Adresse no="6" rue="Avenue Blaise Pascal" codePostal="77420" ville="Marne-la-vallÃ©e"/>
         <Coordonnee lat="48.841050" long="2.587334" />
	</Lieu>
</tsi2016>
